services:
  dropzonebot:
    container_name: dropzonebot
    image: git.postfmly.com/admin/dropzonebot:arm64
    restart: unless-stopped
    ports:
      - "8001:8001"
    volumes:
      - db:/app/db
    environment:
      - LOGO_NAME=dropzonebot.webp
      - LOGO_PATH=./utils/images
      - LOGO_PORT=8001
      - LOGO_URL=https://dropzonebot.postfmly.us/dropzonebot.webp
      - TZ=America/Chicago
    env_file: .env
    labels:
      - wud.display.name=DropZoneBot
      - homepage.group=Personal
      - homepage.name=DropZoneBot
      - homepage.icon=https://dropzonebot.postfmly.com/dropzonebot.webp

volumes:
  db:

networks: {}
